// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwTqj2RC41t0IDJi9YtMBia6pOV0iI4hY',
    appId: '1:199148318823:web:39a13df77408073dada4c2',
    messagingSenderId: '199148318823',
    projectId: 'medicare-6f594',
    authDomain: 'medicare-6f594.firebaseapp.com',
    storageBucket: 'medicare-6f594.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmMywLtLksE5f-p30kzQaqFfAaVPW3IE',
    appId: '1:199148318823:android:c0712251b0483b81ada4c2',
    messagingSenderId: '199148318823',
    projectId: 'medicare-6f594',
    storageBucket: 'medicare-6f594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TBIxH0tSj-JM7R5B_DTWKOMISqC4SnU',
    appId: '1:199148318823:ios:e344757e4116bc18ada4c2',
    messagingSenderId: '199148318823',
    projectId: 'medicare-6f594',
    storageBucket: 'medicare-6f594.firebasestorage.app',
    androidClientId: '199148318823-pk90k1gbppf2cga9hinlj2u4fe6o3okn.apps.googleusercontent.com',
    iosClientId: '199148318823-4mcrhbuigcfu4fcvcag8bo3fsov2j2ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6TBIxH0tSj-JM7R5B_DTWKOMISqC4SnU',
    appId: '1:199148318823:ios:e344757e4116bc18ada4c2',
    messagingSenderId: '199148318823',
    projectId: 'medicare-6f594',
    storageBucket: 'medicare-6f594.firebasestorage.app',
    androidClientId: '199148318823-pk90k1gbppf2cga9hinlj2u4fe6o3okn.apps.googleusercontent.com',
    iosClientId: '199148318823-4mcrhbuigcfu4fcvcag8bo3fsov2j2ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwTqj2RC41t0IDJi9YtMBia6pOV0iI4hY',
    appId: '1:199148318823:web:6f321f243f0a7218ada4c2',
    messagingSenderId: '199148318823',
    projectId: 'medicare-6f594',
    authDomain: 'medicare-6f594.firebaseapp.com',
    storageBucket: 'medicare-6f594.firebasestorage.app',
  );

}